# === config.py: 策略參數設置 ===
API_KEY = "你的API_KEY"
API_SECRET = "你的API_SECRET"

SYMBOL = "ETHUSDT"
LEVERAGE = 20
THRESH_PROB = 0.7
THRESH_RET = 0.004
MAX_POSITION = 0.2
MAX_SINGLE_LOSS = 0.01
TAKE_PROFIT = 0.05
LOOKBACK_N = 5
FUTURE_N = 8        # 使用槓桿倍數
