# === config.py: 策略參數設置 ===
API_KEY = "UH6vSZ9BfxPeaVzVj1tyBEvKlph4U6dGKsmip71fPmgBfhFf0K3PXIHDQNgtbAOi"
API_SECRET = "w9NOqdRvIdtJcGvGiL0fE7kEzOCA7IoHjkP8FaFtznghkouMowcuSxVn5KLTMpG7"

SYMBOL = "ETHUSDT"
LEVERAGE = 20
THRESH_PROB = 0.7
THRESH_RET = 0.004
MAX_POSITION = 0.2
MAX_SINGLE_LOSS = 0.01
TAKE_PROFIT = 0.05
LOOKBACK_N = 5
FUTURE_N = 8        # 使用槓桿倍數
INTERVAL = "4h"
LOOKBACK = 300
MODEL_CLF = "clf_model.pkl"
MODEL_REG = "reg_model.pkl"
